# Nome do site
site_name: "CD - MOJ"

# Descrição
site_description: "Repositório de documentos de Interação Humano-Computador"
repo_name: "2024.2-Grupo05"
repo_url: "https://github.com/Interacao-Humano-Computador/2024.2-Grupo05"

# Configura a navegação do site
nav:
  - Introdução: index.md
  - Atas:
      - Ata padrão: atas/ata-padrao.md
      - Ata 1: atas/ataN1_07_11_2024.md
      - Ata 2: atas/ataN2_30_11_2024.md
  - Entregas:
      - Planejamento:
          - Cronograma Planejado: entregas/entrega_1/cronograma.md
          - Cronograma Executado: entregas/entrega_1/cronograma_executado.md
          - Design: entregas/entrega_1/design.md
          - Ferramentas: entregas/entrega_1/ferramentas.md
          - Heatmap: entregas/entrega_1/heatmap.md
          - Metodologia: entregas/entrega_1/metodologia.md
          - Site escolhido: entregas/entrega_1/site_escolhido.md
          - Sites avaliados: entregas/entrega_1/sites_avaliados.md
          - Entrega: entregas/entrega_1/entrega_1.md
      - Análise de requisitos 1:
          - Aspectos éticos e termo de consentimento: entregas/entrega_2/aspectos_eticos.md
          - Perfil dos usuários: entregas/entrega_2/perfil.md
          - Análise de tarefas Modelo HTA: entregas/entrega_2/analise_de_tarefas/HTA.md
          - Análise de tarefas Modelo GOMS: entregas/entrega_2/analise_de_tarefas/GOMS.md
          - Cenários: entregas/entrega_2/cenarios.md
          - Entrega: entregas/entrega_2/entrega_2.md
      - Análise de requisitos 2:
          - Características da plataforma: entregas/entrega_2/caracteristicas.md
          - Guia de estilo: entregas/entrega_2/guia_de_estilo.md
          - Princípios Gerais: entregas/entrega_3/principiosGerais.md
          - Metas de usabilidade: entregas/entrega_3/metas_de_usabilidade.md
          - Entrega: entregas/entrega_3/entrega_3.md
      - Design, Avaliação e Desenvolvimento:
          - Nível 1:
            - Entrega: entregas/entrega_4/entrega_4.md
            - Storyboard:
                - Planejamento da Avaliação do Storyboard: entregas/entrega_4/storyboard/planejamento_da_avaliação.md
                - Planejamento do Relato dos Resultados do Storyboard: entregas/entrega_4/storyboard/planejamento_do_relato.md
                - Storyboards: entregas/entrega_4/storyboard/storyboards.md
            - Analise de tarefas:
                - Planejamento da Avaliação da Análise de Tarefas: entregas/entrega_4/analise_requisitos/planejamento_avaliacao.md
                - Planejamento do relato de resultados da avaliação da análise de tarefas: entregas/entrega_4/analise_requisitos/planejamento_relato.md
            - Relato resultados storyboard e analise de tarefas: entregas/entrega_5/relato_resultados_storyboard_analise_tarefas.md
          - Nível 2:
              - Entrega: entregas/entrega_5/entrega_5.md
              - Prototipo de papel:
                  - Planejamento avaliação: entregas/entrega_5/prototipo_papel/planejamento_avaliacao.md
                  - Planejamento relato: entregas/entrega_5/prototipo_papel/planejamento_relato.md
              - Relato resultados prototipo de papel: 
                  - Felipe Rodrigues: entregas/entrega_6/relatos_de_resultados_prototipo_de_papel/relato_FelipeRodrigues.md
                  - Jéssica Eveline: entregas/entrega_6/relatos_de_resultados_prototipo_de_papel/relato_JessicaEveline.md
                  - João Vitor: entregas/entrega_6/relatos_de_resultados_prototipo_de_papel/relato_JoãoVitor.md
                  - Ruan Carvalho: entregas/entrega_6/relatos_de_resultados_prototipo_de_papel/relato_RuanCarvalho.md
          - Nível 3:
              - Entregas: 
                  - Entrega 6: entregas/entrega_6/entrega_6.md
                  - Entrega 7: entregas/entrega_7/entrega_7.md
              - Prototipo de alta fidelidade:
                  - Planejamento avaliação: entregas/entrega_6/prototipo_alta_fidelidade/planejamento_avaliacao.md
                  - Planejamento relato: entregas/entrega_6/prototipo_alta_fidelidade/planejamento_relato.md
              - Relato dos Resultados dos Protótipos de Alta Fidelidade:
                  - Felipe Rodrigues:  entregas/entrega_7/relatos_de_resultados_prototipos_de_alta_fidelidade/relato_FelipeRodrigues.md
                  - Ruan Carvalho:  entregas/entrega_7/relatos_de_resultados_prototipos_de_alta_fidelidade/relato_RuanCarvalho.md
                  - Jéssica Eveline:  entregas/entrega_7/relatos_de_resultados_prototipos_de_alta_fidelidade/relato_JessicaEveline.md
      - Avaliações:   
          - Autoavaliação: entregas/avaliações/autoavaliação_1.md
          - Avaliação Grupo 6: entregas/avaliações/avaliação_grupo06_1.md

# Tema do MkDocs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
  favicon: https://moj.naquadah.com.br/images/logo_moj.png
  logo: https://moj.naquadah.com.br/images/logo_moj.png

extra:
  version:
    provider: felipe

extra_css: [stylesheets/extra.css]
