# Nome do site
site_name: "CD - MOJ"

# Descrição
site_description: "Repositório de documentos de Interação Humano-Computador"
repo_name: "2024.2-Grupo05"
repo_url: "https://github.com/Interacao-Humano-Computador/2024.2-Grupo05"

# Configura a navegação do site
nav:
  - Introdução: README.md
  - Atas:
      - Ata 1: atas/ataN1_07_11_2024.md
  - Planejamento:
      - Cronograma Planejado: planejamento/cronograma.md
      - Cronograma Executado: planejamento/cronograma_executado.md
      - Design: planejamento/design.md
      - Ferramentas: planejamento/ferramentas.md
      - Heatmap: planejamento/heatmap.md
      - Site escolhido: planejamento/site-escolhido.md
      - Sites avaliados: planejamento/sites-avaliados.md
  - Entregas:
      - Entrega 1: entregas/entrega_1.md
  - Verificação:
      - Entrega 1:
        - Lista de Verificação: SUBSTITUIRPELALISTA.md
        - Lista de Verificação Grupo+1: SUBSTITUIRPELALISTA.md

# Tema do MkDocs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
  favicon: https://moj.naquadah.com.br/images/logo_moj.png
  logo: https://moj.naquadah.com.br/images/logo_moj.png

extra:
  version:
    provider: felipe

extra_css: [stylesheets/extra.css]
